name: adamwgs_3dgs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ld_impl_linux-64=2.38=h1181459_1
  - ncurses=6.4=h6a678d5_0
  - numpy-base=1.21.5=py37ha15fc14_3
  - pip=22.3.1=py37h06a4308_0
  - plyfile=0.8.1=pyhd8ed1ab_0
  - python=3.7.13=haa1d7c7_1
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tqdm=4.64.1=py37h06a4308_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - matplotlib==3.5.3
    - numpy==1.21.6
    - openpyxl==3.1.3
    - packaging==24.0
    - pillow==9.3.0
    - scipy==1.7.3
    - setuptools==57.5.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2.2
    - torch==1.12.1+cu116
    - torchaudio==0.12.1+cu116
    - torchvision==0.13.1+cu116
